// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// Auto-generated by swift-openapi-bootstrapper
// Generated at: 2026-07-25T19:47:39.720449

import PackageDescription

let package = Package(
    name: "SwiftOpenaiApi",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        .library(
            name: "SwiftOpenaiApiTypes",
            targets: ["SwiftOpenaiApiTypes"]
        ),
        .library(
            name: "SwiftOpenaiApiRealtimeTypes",
            targets: ["SwiftOpenaiApiRealtimeTypes"]
        ),
        .library(
            name: "SwiftOpenaiApi",
            targets: ["SwiftOpenaiApi"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-generator.git", from: "1.10.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.8.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-async-http-client", from: "1.1.0"),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.0.0"),
    ],
    targets: [
        // Types target: Contains generated types from OpenAPI spec
        .target(
            name: "SwiftOpenaiApiTypes",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime")
            ]
        ),
        // Realtime target: Contains generated WebSocket event types
        .target(
            name: "SwiftOpenaiApiRealtimeTypes",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime")
            ]
        ),
        // Client target: Contains generated client and custom code
        .target(
            name: "SwiftOpenaiApi",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIAsyncHTTPClient", package: "swift-openapi-async-http-client"),
                .target(name: "SwiftOpenaiApiTypes"),
            ]
        ),
        // Tests
        .testTarget(
            name: "SwiftOpenaiApiTests",
            dependencies: [
                .target(name: "SwiftOpenaiApi"),
                .target(name: "SwiftOpenaiApiTypes"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            resources: [.copy("Resources")]
        ),
        .testTarget(
            name: "SwiftOpenaiApiRealtimeTypesTests",
            dependencies: [
                .target(name: "SwiftOpenaiApiRealtimeTypes")
            ]
        ),
    ]
)
