// Auto-generated by swift-openapi-bootstrapper

import OpenAPIAsyncHTTPClient
import OpenAPIRuntime
import SwiftOpenaiApi
import SwiftOpenaiApiTypes
import Testing
import UsefulThings

#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
@preconcurrency import struct Foundation.UUID
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
import struct Foundation.UUID
#endif

struct SwiftOpenaiApiTests {
    let client = {

        let envFileUrl = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent(".env")
        let apiKey = UsefulThings.getEnvironmentVariable("OPENAI_API_KEY", from: envFileUrl)!
        return Client(
            serverURL: try! Servers.Server1.url(),
            transport: AsyncHTTPClientTransport(),
            middlewares: [
                AuthenticationMiddleware(apiKey: apiKey)
            ]
        )
    }()

    @Test func exampleChatCompletion() async throws {
        let response = try await client.createChatCompletion(
            body: Operations.createChatCompletion.Input.Body.json(
                .init(
                    value1: Components.Schemas.CreateModelResponseProperties.init(
                        value1: Components.Schemas.ModelResponseProperties.init(
                            metadata: Components.Schemas.Metadata.init(additionalProperties: ["my_metadata": "my_value"]),
                            top_logprobs: nil,  // The 'top_logprobs' parameter is only allowed when 'logprobs' is enabled.,
                            temperature: 1,
                            top_p: Double?.none,
                            user: String?.none,
                            safety_identifier: UUID().uuidString,
                            prompt_cache_key: "Stable key for similar requests",
                            service_tier: Components.Schemas.ServiceTier.auto,
                            prompt_cache_retention: Components.Schemas.ModelResponseProperties.prompt_cache_retentionPayload._24h
                        ),
                        value2: Components.Schemas.CreateModelResponseProperties.Value2Payload.init(
                            prompt_cache_options: Components.Schemas.PromptCacheOptionsParam.init(
                                ttl: Components.Schemas.PromptCacheTTLEnum._30m,
                                mode: Components.Schemas.PromptCacheModeEnum.implicit
                            ),
                            top_logprobs: nil  // The 'top_logprobs' parameter is only allowed when 'logprobs' is enabled.
                        )
                    ),
                    value2: Components.Schemas.CreateChatCompletionRequest.Value2Payload.init(
                        messages: [
                            Components.Schemas.ChatCompletionRequestMessage.ChatCompletionRequestSystemMessage(
                                Components.Schemas.ChatCompletionRequestSystemMessage.init(
                                    content: .case1("You are a helpful assistant."),
                                    role: Components.Schemas.ChatCompletionRequestSystemMessage.rolePayload.system
                                )
                            ),
                            Components.Schemas.ChatCompletionRequestMessage.ChatCompletionRequestUserMessage(
                                Components.Schemas.ChatCompletionRequestUserMessage.init(
                                    content: Components.Schemas.ChatCompletionRequestUserMessage.contentPayload.case1("How are you?"),
                                    role: Components.Schemas.ChatCompletionRequestUserMessage.rolePayload.user
                                )
                            ),
                        ],
                        model: Components.Schemas.ModelIdsShared.init(
                            value1: String?.none,
                            value2: Components.Schemas.ModelIdsShared.Value2Payload.gpt_hyphen_5_period_6_hyphen_luna
                        ),
                        modalities: Components.Schemas.ResponseModalities?.none, // Unknown parameter: 'modalities'
                        verbosity: Components.Schemas.Verbosity.high,
                        reasoning_effort: Components.Schemas.ReasoningEffort.low,
                        max_completion_tokens: Int?.none,
                        frequency_penalty: Double?.none,
                        presence_penalty: Double?.none,
                        web_search_options: nil, // Unknown parameter: 'web_search_options'.
                        // web_search_options: Components.Schemas.CreateChatCompletionRequest.Value2Payload.web_search_optionsPayload.init(
                        //     user_location:
                        //         Components.Schemas.CreateChatCompletionRequest.Value2Payload.web_search_optionsPayload.user_locationPayload.init(
                        //             _type: Components.Schemas.CreateChatCompletionRequest.Value2Payload.web_search_optionsPayload.user_locationPayload._typePayload.approximate,
                        //             approximate: Components.Schemas.WebSearchLocation.init(country: "USA", region: "CA", city: "SF", timezone: String?.none)
                        //         ),
                        //     search_context_size: Components.Schemas.WebSearchContextSize.low
                        // ),
                        top_logprobs: Int?.none,
                        response_format: Components.Schemas.CreateChatCompletionRequest.Value2Payload.response_formatPayload.ResponseFormatText(
                            Components.Schemas.ResponseFormatText.init(
                                _type: Components.Schemas.ResponseFormatText._typePayload.text
                            )
                        ),
                        audio: Components.Schemas.CreateChatCompletionRequest.Value2Payload.audioPayload?.none,
                        store: true,
                        moderation: Components.Schemas.ModerationParam?.none,
                        stream: false,
                        stop: Components.Schemas.StopConfiguration?.none,
                        logit_bias: Components.Schemas.CreateChatCompletionRequest.Value2Payload.logit_biasPayload?.none,
                        logprobs: Bool?.none,
                        max_tokens: Int?.none,
                        n: Int?.none,
                        prediction: Components.Schemas.PredictionContent?.none,
                        seed: Int?.none,
                        stream_options: Components.Schemas.ChatCompletionStreamOptions?.none,
                        tools: Components.Schemas.CreateChatCompletionRequest.Value2Payload.toolsPayload?.none,
                        tool_choice: Components.Schemas.ChatCompletionToolChoiceOption?.none,
                        parallel_tool_calls: Components.Schemas.ParallelToolCalls?.none,
                        function_call: Components.Schemas.CreateChatCompletionRequest.Value2Payload.function_callPayload?.none,
                        functions: [Components.Schemas.ChatCompletionFunctions]?.none
                    )
                )
            )
        )

        dump(response)
    }
}
