// Auto-generated by swift-openapi-bootstrapper

import OpenAPIAsyncHTTPClient
import OpenAPIRuntime
import SwiftOpenaiApi
import SwiftOpenaiApiTypes
import Testing
import UsefulThings

#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif

struct SwiftOpenaiApiTests {
    let client = {

        let envFileUrl = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent(".env")
        let apiKey = UsefulThings.getEnvironmentVariable("OPENAI_API_KEY", from: envFileUrl)!
        return Client(
            serverURL: try! Servers.Server1.url(),
            transport: AsyncHTTPClientTransport(),
            middlewares: [
                AuthenticationMiddleware(apiKey: apiKey)
            ]
        )
    }()

    @Test func example() async throws {
        // let response = try await client.<#method#>(
        //
        // )
    }
}
