// AuthenticationMiddleware.swift
// Auto-generated by swift-openapi-bootstrapper
// Security Scheme: ApiKeyAuth

import Foundation
import OpenAPIRuntime
import HTTPTypes

public struct AuthenticationMiddleware: ClientMiddleware {
    public var apiKey: String

    public init(apiKey: String) {
        self.apiKey = apiKey
    }

    public func intercept(
        _ request: HTTPRequest,
        body: HTTPBody?,
        baseURL: URL,
        operationID: String,
        next: (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
    ) async throws -> (HTTPResponse, HTTPBody?) {
        var request = request

        // HTTP Bearer Token Authentication
        request.headerFields[.authorization] = "Bearer \(apiKey)"

        return try await next(request, body, baseURL)
    }
}
